from pydantic import BaseModel

class Todo(BaseModel):
    REC_ID: str
YEAR: int
MONTH: str
CONTRACT_NO: str
LOANMASTER_ID: int
ME_USERNAME: str
ME_AD: str
MONTH_START_STATUS: str
MONTH_END_STATUS: str
LOAN_EXPIRE_DATE: str
LOAN_START_DATE: str
LOAN_AMOUNT: int
PRODUCT_ID: int
PRODUCT_NAME: str
LOAN_PRODUCT_ID: int
LOAN_PRODUCT_NAME: str
MONTH_START_DPD_DATE: str
MONTH_START_DPD: int
MONTH_MAX_DPD: int
MONTH_END_DPD_DATE: str
MONTH_END_DPD: int
MONTH_START_ARR: int
MONTH_MAX_ARR: int
MONTH_END_ARR: int
